---
title: "Code_Handout"
author: "Jackie Vogel, Sarah Millard, Ignacio Luque, Leo Walker"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# installing caret for train/test split
library(caret)
library(nnet)
```

## Multinomial Logistic Regression

This R Markdown demonstrates how to use Multinomial Logistic Regression on a small dataset that is predicting which drug to presecribe to a patient.

dataset was found at https://www.kaggle.com/datasets/jeevanrh/drug200csv


```{r}
drug <-read.csv("../data/drug200.csv", header=TRUE, sep= ",")
str(drug)
```

## Change the chr types to factors


```{r}
drug$Sex <- as.factor(drug$Sex)
drug$BP <- as.factor(drug$BP)
drug$Cholesterol <- as.factor(drug$Cholesterol)
drug$Drug <- as.factor(drug$Drug)
```

## Check for multicollinearity between variables?

```{r}

````

## Splitting the data in train and test

```{r}
#Splitting the data using a function from dplyr package
index <- createDataPartition(drug$Drug, p = .70, list = FALSE)
train <- drug[index,]
test <- drug[-index,]

````

## Train the model

```{r}
# Training the multinomial model
multinom_model <- multinom(Drug ~ ., data = train)

# Checking the model
summary(multinom_model)
````

## Step

```{r}
exp(coef(multinom_model))
# Predicting the values for train dataset
train$DrugPredicted <- predict(multinom_model, newdata = train, "class")
# Building classification table
tab <- table(train$Drug, train$DrugPredicted)
# Calculating accuracy - sum of diagonal elements divided by total obs
round((sum(diag(tab))/sum(tab))*100,2)
````

## Step

```{r}
# Predicting the class for test dataset
test$DrugPredicted <- predict(multinom_model, newdata = test, "class")
# Building classification table
tab <- table(test$Drug, test$DrugPredicted)
tab
````








